name: Daily Football Scraper

on:
  schedule:
    - cron: '30 22 * * *'
  workflow_dispatch: 

jobs:
  scrape-job:
    runs-on: ubuntu-latest
    # ဒီအပိုင်း ပါဝင်ရပါမယ်
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: curl

      - name: Run Scraper Script
        run: php scraper.php

      - name: Commit and Push if changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add football_data.json
          # ပြောင်းလဲမှုရှိမှသာ commit လုပ်မယ်၊ မရှိရင် error မတက်အောင် exit 0 သုံးမယ်
          git commit -m "Update data: $(date)" || echo "No changes to commit"
          git push
